#!/usr/bin/env bash

# Shared configuration for every operator-facing launcher.
COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$COMMON_DIR/.." && pwd)"

if [[ -f "$PROJECT_ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$PROJECT_ROOT/.env"
  set +a
fi

NERO_WS="${NERO_WS:-$HOME/nero_ws}"
NERO_TELEOP_SRC="${NERO_TELEOP_SRC:-$PROJECT_ROOT/src}"
NERO_TELEOP_PYTHON="${NERO_TELEOP_PYTHON:-$NERO_WS/.venv/bin/python}"
NERO_LEROBOT_PYTHON="${NERO_LEROBOT_PYTHON:-$HOME/enter/envs/lerobot/bin/python}"
NERO_TELEOP_ARTIFACTS_DIR="${NERO_TELEOP_ARTIFACTS_DIR:-$PROJECT_ROOT/artifacts}"
NERO_BIMANUAL_DATA_DIR="${NERO_BIMANUAL_DATA_DIR:-$HOME/nero_data/raw/towel_fold}"

PICO_LEFT_CAN_PORT="${PICO_LEFT_CAN_PORT:-can_left}"
PICO_RIGHT_CAN_PORT="${PICO_RIGHT_CAN_PORT:-can_right}"
PICO_LEFT_CAN_USB_BUS="${PICO_LEFT_CAN_USB_BUS:-1-2.3:1.0}"
PICO_RIGHT_CAN_USB_BUS="${PICO_RIGHT_CAN_USB_BUS:-3-1.2:1.0}"

export PROJECT_ROOT NERO_WS NERO_TELEOP_SRC NERO_TELEOP_PYTHON
export NERO_LEROBOT_PYTHON NERO_TELEOP_ARTIFACTS_DIR NERO_BIMANUAL_DATA_DIR
export PICO_LEFT_CAN_PORT PICO_RIGHT_CAN_PORT
export PICO_LEFT_CAN_USB_BUS PICO_RIGHT_CAN_USB_BUS
export PYTHONPATH="$NERO_TELEOP_SRC:$NERO_WS:$NERO_WS/src/pyAgxArm${PYTHONPATH:+:$PYTHONPATH}"
